# Override file for development/testing
# This file is automatically loaded by docker-compose
# Use: docker-compose -f docker-compose.prod.yml -f docker-compose.override.yml up

version: '3.8'

services:
  # Override for development
  backend:
    environment:
      - APP_DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ../eagle:/var/www/html
      - ../eagle/storage:/var/www/html/storage

  frontend:
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8000
      - VUE_APP_APP_URL=http://localhost:3000
    volumes:
      - ../eagle-front:/app
      - /app/node_modules
